---
# Copyright (C) 2026 Patryk Ściborek <patryk@sciborek.com>
# Copyright (C) 2026 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage Garage S3 object store
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_garage' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare garage environment
      ansible.builtin.import_role:
        name: 'garage'
        tasks_from: 'main_env'
      tags: [ 'role::garage', 'role::secret', 'role::etc_services',
              'role::ferm', 'role::nginx' ]

  roles:

    - role: secret
      tags: [ 'role::secret', 'role::garage' ]
      secret__directories: '{{ garage__secret_directories }}'

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ garage__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ garage__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules }}'

    - role: python
      tags: [ 'role::python', 'skip::python' ]
      python__dependent_packages3:
        - '{{ nginx__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ nginx__python__dependent_packages2 }}'

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_upstreams:
        - '{{ garage__nginx__dependent_upstreams }}'
      nginx__dependent_servers:
        - '{{ garage__nginx__dependent_servers }}'

    - role: garage
      tags: [ 'role::garage', 'skip::garage' ]
