---
# Copyright (C) 2022 Patryk Ściborek <patryk@sciborek.com>
# Copyright (C) 2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage Zigbee2MQTT service
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'debops_service_zigbee2mqtt' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::nodejs', 'role::nginx' ]
      keyring__dependent_apt_keys:
        - '{{ nodejs__keyring__dependent_apt_keys }}'
        - '{{ nginx__keyring__dependent_apt_keys if (zigbee2mqtt__frontend_enabled|bool) else []}}'

    - role: apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences', 'role::nodejs', 'role::nginx' ]
      apt_preferences__dependent_list:
        - '{{ nodejs__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list if (zigbee2mqtt__frontend_enabled|bool) else [] }}'

    - role: nodejs
      tags: [ 'role::nodejs', 'skip::nodejs' ]

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'
      when: zigbee2mqtt__frontend_enabled|bool

    - role: python
      tags: [ 'role::python', 'skip::python' ]
      python__dependent_packages3:
        - '{{ nginx__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ nginx__python__dependent_packages2 }}'
      when: zigbee2mqtt__frontend_enabled|bool

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_servers:
        - '{{ zigbee2mqtt__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ zigbee2mqtt__nginx__dependent_upstreams }}'
      when: zigbee2mqtt__frontend_enabled|bool

    - role: zigbee2mqtt
      tags: [ 'role::zigbee2mqtt', 'skip::zigbee2mqtt' ]
